### PR TITLE
Harmony: Comment form

### LINKED ISSUE #813: Harmony: Comment form
1. Comment view - burger button is a transparent xs-sized button with a 24px clickfield
2. Status bar for status updates - text color is from the status, add a second field for the background color
3. New/edit comment field - keep old editor
4. Update reactions dropdown to a harmony one

### PR DESCRIPTION
**Pull request by asabotovich**
## PR includes

- [x] Feature

## Related issues

Resolve #813 

## QA Instructions, Screenshots, Recordings
  
Screenshot 2024-04-04 at 19 00 59

### CODE REVIEW

**Comment by asabotovich** [comment]
Screenshot 2024-04-05 at 11 33 20

**Review by DenisVorop — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]

**Pull request merged**
