### PR TITLE
Kanban Card

### LINKED ISSUE #1111: Kanban Card

### PR DESCRIPTION
**Pull request by asabotovich**
## PR includes

- [x] Feature

## Related issues

Resolve #1111

## QA Instructions, Screenshots, Recordings
  
Снимок экрана 2024-07-30 в 16 57 44

### CODE REVIEW

**Review by tsumo — APPROVED** [review]

**Comment by tsumo** [comment]
It's spelled kanban...

**Review by LamaEats — APPROVED** [review]

**Pull request merged**
