### PR TITLE
AutoComplete enable keypress navigation

### LINKED ISSUE #772: AutoComplete enable keypress navigation
The up/down arrow doesn't work.

### PR DESCRIPTION
**Pull request by asabotovich**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #772 

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/bricks/assets/9020793/7ac07f58-42ad-4aaa-828a-288afa3aec02

### CODE REVIEW

**Comment by asabotovich** [comment]
After #753

**Review by awinogradov — CHANGES_REQUESTED** [review]
image

Do u need help to enable linters localy?

**Comment by asabotovich** [comment]
harmony 

https://github.com/taskany-inc/bricks/assets/9020793/4bf3d04c-344a-4a77-9a97-60590a8b6504

**Review by awinogradov — APPROVED** [review]

**Pull request merged**
