### PR TITLE
Harmony: FormControl

### LINKED ISSUE #812: Harmony: FormControl

### PR DESCRIPTION
**Pull request by DenisVorop**
## PR includes

- [x] Feature

## Related issues

Resolve #812 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/bricks/assets/95316053/e6a9ee75-423c-419b-9bc5-dfadc17571c1

### CODE REVIEW

**Review by awinogradov — APPROVED** [review]

**Comment by awinogradov** [comment]
image

**Comment by awinogradov** [comment]
Incorrect icon

**Review by tsumo — APPROVED** [review]

**Comment by DenisVorop** [comment]
Снимок экрана 2024-02-08 в 12 40 08

**Pull request merged**
